export const FALLBACK_PRODUCTS = [
  {
    name: "VCI Film Rolls",
    num: "01",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-film-roll.png",
    slug: "vci-film-rolls",
    shortDescription: "Industrial-grade VCI film rolls for automated packaging lines with superior multimetal corrosion protection.",
    description: "Our VCI Film Rolls are engineered for continuous automated packaging lines in heavy industries. The films release volatile corrosion inhibitors that form an invisible molecular layer on metal surfaces, providing superior multimetal corrosion protection for both ferrous and non-ferrous metals. Manufactured from premium virgin LDPE blended with proprietary VCI additives, these rolls maintain excellent tensile strength, puncture resistance, and optical clarity. Available in custom widths from 100mm to 2000mm and thicknesses from 50 to 200 microns, they are the go-to solution for automotive, aerospace, and steel processing plants across India and internationally.",
    gallery: [
      "/images/rayzor/products/vci-film-roll.png",
      "/images/rayzor/products/vci-engine-wrap.png",
      "/images/rayzor/products/vci-paper-roll.png",
      "/images/rayzor/products/vci-paper-apply.png",
    ],
    features: [
      "Multimetal corrosion protection (ferrous & non-ferrous)",
      "High tensile strength & puncture resistance",
      "Compatible with automated packaging lines",
      "Transparent for easy visual inspection",
      "Custom widths from 100mm to 2000mm",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE + VCI Additives" },
      { label: "Thickness", value: "50 – 200 microns" },
      { label: "Width", value: "100mm – 2000mm" },
      { label: "Roll Length", value: "Up to 1000m" },
      { label: "Protection Period", value: "Up to 24 months" },
      { label: "Compliance", value: "MIL-PRF-22019 / MIL-I-22110C" },
    ],
    tags: ["Made in India", "Custom Sizes", "Corrosion Resistant"],
    applications: ["Automotive", "Aerospace & Defense", "Heavy Machinery", "Steel & Metal Processing", "Electronics", "Export Packaging"],
  },
  {
    name: "VCI Pouch",
    num: "02",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-pouch.png",
    slug: "vci-pouch",
    shortDescription: "Pre-formed VCI pouches for rapid individual component packaging with long-term rust prevention.",
    description: "Our VCI Pouches are pre-formed protective enclosures designed for the rapid packaging of individual metal components. Each pouch is infused with volatile corrosion inhibitors that activate immediately upon sealing, creating an invisible protective shield around spare parts, bearings, fasteners, and small precision metal items. The pouches are available in heat-sealable and self-sealing zip-lock configurations, in transparent or tinted variants for easy product identification. With protection lasting up to 24 months, they are the ideal solution for spare part kitting, after-market distribution, and long-term warehousing of corrosion-sensitive components.",
    gallery: [
      "/images/rayzor/products/vci-pouch.png",
      "/images/rayzor/products/vci-emitter-pad.png",
      "/images/rayzor/products/emitter-pad-apply.png",
      "/images/rayzor/products/vci-sheet.png",
    ],
    features: [
      "Pre-formed for quick packing of individual parts",
      "Ideal for spare parts, bearings & fasteners",
      "Heat-sealable & self-sealing options",
      "Transparent or tinted variants available",
      "Long-term rust prevention up to 24 months",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE + VCI Compound" },
      { label: "Thickness", value: "75 – 150 microns" },
      { label: "Sizes", value: "Custom (50mm × 50mm to 600mm × 900mm)" },
      { label: "Seal Type", value: "Heat seal / Zip lock" },
      { label: "Protection Period", value: "Up to 24 months" },
    ],
    tags: ["Made in India", "Custom Sizes", "Corrosion Resistant"],
    applications: ["Spare Parts", "Bearings & Fasteners", "Precision Instruments", "Electronics", "Automotive Components"],
  },
  {
    name: "VCI Bags",
    num: "03",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-bags.png",
    slug: "vci-bags",
    shortDescription: "Heavy-duty VCI bags for bulk packaging with active corrosion neutralization during shipping and storage.",
    description: "Our VCI Bags are heavy-duty protective bags designed for bulk packaging of larger metal components, assemblies, and machinery parts. Manufactured from LDPE or HM-HDPE blended with VCI additives, each bag creates a dry, protective microclimate that actively neutralizes corrosive elements such as moisture, salt spray, and industrial pollutants. Available in flat, gusseted, and tubular configurations with sizes up to 2500mm × 3000mm, they provide corrosion protection for up to 36 months. Custom printing with your branding, handling instructions, or part numbers is available on all variants.",
    gallery: [
      "/images/rayzor/products/vci-bags.png",
      "/images/rayzor/products/vci-engine-wrap.png",
      "/images/rayzor/products/foil-barrier-bag.png",
      "/images/rayzor/products/vci-film-roll.png",
    ],
    features: [
      "Heavy-duty construction for bulk packaging",
      "Creates protective microclimate inside bag",
      "Neutralizes corrosive elements actively",
      "Available in flat, gusseted & tubular styles",
      "Custom printing available",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE / HM-HDPE + VCI" },
      { label: "Thickness", value: "100 – 250 microns" },
      { label: "Max Size", value: "Up to 2500mm × 3000mm" },
      { label: "Style", value: "Flat / Gusseted / Tubular" },
      { label: "Protection Period", value: "Up to 36 months" },
    ],
    tags: ["Made in India", "Custom Sizes", "Corrosion Resistant"],
    applications: ["Heavy Machinery", "Engine Components", "Steel Coils", "Defense Equipment", "Export Crating"],
  },
  {
    name: "VCI Sheet",
    num: "04",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-sheet.png",
    slug: "vci-sheet",
    shortDescription: "Versatile VCI sheets for interleaving stacked metal parts and lining export crates.",
    description: "Our VCI Sheets are versatile, flat-cut protective films used as interleaving between stacked metal parts, liners for export crates, or wrapping material for oddly shaped components. The sheets begin releasing volatile corrosion inhibitors immediately upon contact with the enclosed airspace, providing instant vapor-phase protection to all exposed metal surfaces. They are easy to cut and handle on the production floor and are compatible with all common ferrous and non-ferrous metals. Ideal for CNC machined parts, sheet metal components, stamped parts, and automotive sub-assemblies.",
    gallery: [
      "/images/rayzor/products/vci-sheet.png",
      "/images/rayzor/products/vci-paper-apply.png",
      "/images/rayzor/products/vci-paper-roll.png",
      "/images/rayzor/products/vci-emitter-pad.png",
    ],
    features: [
      "Versatile interleaving for stacked metal parts",
      "Protective liner for export crates & pallets",
      "Immediate vapor-phase corrosion inhibition",
      "Easy to cut and handle on production floor",
      "Compatible with all common metals",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE + VCI Additives" },
      { label: "Thickness", value: "50 – 200 microns" },
      { label: "Sheet Sizes", value: "Custom cut to order" },
      { label: "Protection", value: "Ferrous & Non-ferrous metals" },
      { label: "Protection Period", value: "Up to 24 months" },
    ],
    tags: ["Made in India", "Custom Sizes", "Corrosion Resistant"],
    applications: ["Metal Stamping", "CNC Machined Parts", "Sheet Metal", "Automotive Parts", "Warehousing"],
  },
  {
    name: "LDPE Film Rolls",
    num: "05",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-film-roll.png",
    slug: "ldpe-film-rolls",
    shortDescription: "High-clarity virgin LDPE film rolls with exceptional stretch, tear resistance, and moisture barrier properties.",
    description: "Our LDPE Film Rolls are manufactured from 100% virgin Low-Density Polyethylene, offering exceptional stretch, tear resistance, and barrier properties. These rolls form the foundation for secure, moisture-resistant industrial packaging across a wide range of sectors. With high optical clarity and consistent gauge throughout, they are suitable for both manual and automated packaging lines. Available in thicknesses from 25 to 300 microns and widths up to 2500mm, with options for custom colors, printing, and FDA-compliant food-grade formulations.",
    gallery: [
      "/images/rayzor/products/ldpe-film-roll.png",
      "/images/rayzor/products/ldpe-sheet-roll.png",
      "/images/rayzor/products/ldpe-machinery-cover.png",
      "/images/rayzor/products/pallet-wrap-apply.png",
    ],
    features: [
      "High-clarity virgin LDPE material",
      "Exceptional stretch & tear resistance",
      "Superior moisture barrier properties",
      "FDA-compliant grades available",
      "Custom colors and printing options",
    ],
    technicalSpecs: [
      { label: "Material", value: "Virgin LDPE" },
      { label: "Thickness", value: "25 – 300 microns" },
      { label: "Width", value: "50mm – 2500mm" },
      { label: "Clarity", value: "High transparency" },
      { label: "Tensile Strength", value: "15 – 30 MPa" },
    ],
    tags: ["Made in India", "Custom Sizes", "Moisture Resistant"],
    applications: ["General Packaging", "Food Industry", "Pharmaceutical", "Textile", "Agriculture", "Construction"],
  },
  {
    name: "LDPE Pouch",
    num: "06",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-pouch.png",
    slug: "ldpe-pouch",
    shortDescription: "Durable LDPE pouches with excellent moisture and dust barriers in multiple thickness options.",
    description: "Our LDPE Pouches provide durable, reliable protection for individual items across a wide range of industries. Each pouch offers an excellent moisture and dust barrier, keeping contents clean and dry during storage and transit. Available in thicknesses ranging from 40 to 200 microns, with heat-sealable construction for tamper-evident closure. Choose from plain or custom-printed variants to match your branding requirements. Made from recyclable virgin LDPE material, these pouches are an eco-conscious choice for responsible industrial packaging.",
    gallery: [
      "/images/rayzor/products/ldpe-pouch.png",
      "/images/rayzor/products/ldpe-bags.png",
      "/images/rayzor/products/ldpe-film-roll.png",
    ],
    features: [
      "Excellent moisture & dust barrier",
      "Multiple thickness options",
      "Heat-sealable construction",
      "Available in plain or printed variants",
      "Recyclable material",
    ],
    technicalSpecs: [
      { label: "Material", value: "Virgin LDPE" },
      { label: "Thickness", value: "40 – 200 microns" },
      { label: "Sizes", value: "Custom (50mm × 75mm to 500mm × 700mm)" },
      { label: "Seal Type", value: "Heat seal / Adhesive" },
    ],
    tags: ["Made in India", "Custom Sizes", "Moisture Resistant"],
    applications: ["Hardware Parts", "Textile", "Consumer Goods", "Electronics Accessories", "Stationery"],
  },
  {
    name: "LDPE Bags",
    num: "07",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-bags.png",
    slug: "ldpe-bags",
    shortDescription: "Industrial-strength LDPE bags for bulk handling with excellent sealability and puncture resistance.",
    description: "Our LDPE Bags are built for the demands of industrial bulk handling and secondary packaging. Manufactured from a premium LDPE/LLDPE blend, they deliver outstanding sealability and puncture resistance, making them ideal for heavy or sharp contents. Available in flat, gusseted, and side-seal configurations with sizes up to 2000mm × 2500mm and thicknesses from 50 to 300 microns. Whether you need bags for component kitting, bulk parts storage, or retail distribution, our LDPE bags can be customized to your exact specifications including size, thickness, color, and printing.",
    gallery: [
      "/images/rayzor/products/ldpe-bags.png",
      "/images/rayzor/products/ldpe-pouch.png",
      "/images/rayzor/products/ldpe-sheet.png",
      "/images/rayzor/products/ldpe-film-roll.png",
    ],
    features: [
      "Industrial-strength for bulk handling",
      "Excellent sealability",
      "High puncture resistance",
      "Flat, gusseted & side-seal options",
      "Custom sizes & thicknesses",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE / LLDPE blend" },
      { label: "Thickness", value: "50 – 300 microns" },
      { label: "Max Size", value: "Up to 2000mm × 2500mm" },
      { label: "Style", value: "Flat / Gusseted / Side seal" },
    ],
    tags: ["Made in India", "Custom Sizes", "Moisture Resistant"],
    applications: ["Industrial Components", "Bulk Packaging", "Warehousing", "Export", "Retail"],
  },
  {
    name: "LDPE Sheet",
    num: "08",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-sheet.png",
    slug: "ldpe-sheet",
    shortDescription: "Thick LDPE sheeting for pallet capping, surface protection, and large-scale moisture barriers.",
    description: "Our LDPE Sheets are thick-gauge polyethylene sheeting designed for heavy-duty industrial applications. Used extensively for pallet capping, surface protection during transit, and creating large-scale moisture barriers in export packaging, these sheets offer reliable performance in demanding environments. Available in widths up to 6000mm (centre-folded) and thicknesses from 100 to 400 microns, with UV-stabilized options for outdoor storage. The sheets can be supplied in rolls or custom-cut flat sheets to match your specific pallet or crate dimensions.",
    gallery: [
      "/images/rayzor/products/ldpe-sheet.png",
      "/images/rayzor/products/ldpe-sheet-roll.png",
      "/images/rayzor/products/ldpe-machinery-cover.png",
      "/images/rayzor/products/pallet-wrap-apply.png",
    ],
    features: [
      "Thick gauge for heavy-duty applications",
      "Ideal for pallet capping & wrapping",
      "Large-scale moisture barrier",
      "Surface protection during transit",
      "UV-stabilized options available",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE" },
      { label: "Thickness", value: "100 – 400 microns" },
      { label: "Width", value: "Up to 6000mm (folded)" },
      { label: "Length", value: "Custom cut or roll" },
    ],
    tags: ["Made in India", "Custom Sizes", "Moisture Resistant"],
    applications: ["Pallet Wrapping", "Surface Protection", "Construction", "Agriculture", "Export Packaging"],
  },
  {
    name: "Pallet Covers",
    num: "09",
    category: "Specialty Films",
    image: "/images/rayzor/products/pallet-covers.png",
    slug: "pallet-covers",
    shortDescription: "Gusseted pallet covers for standard export pallets with dust, dirt, and moisture protection.",
    description: "Our Pallet Covers are gusseted protective covers designed to perfectly fit standard and custom export pallets. They provide immediate all-round protection against dust, dirt, moisture, and UV exposure during warehouse storage, transit, and open-yard stacking. Available in plain LDPE and VCI-infused variants for corrosion-sensitive cargo, these covers can be quickly applied and removed without tools. Standard sizes fit 1220mm × 1220mm pallets with heights up to 1500mm, with custom dimensions available on request.",
    gallery: [
      "/images/rayzor/products/pallet-covers.png",
      "/images/rayzor/products/pallet-wrap-apply.png",
      "/images/rayzor/products/ldpe-machinery-cover.png",
    ],
    features: [
      "Gusseted design for perfect pallet fit",
      "Protection against dust, dirt & moisture",
      "Standard & custom pallet sizes",
      "Available in plain or VCI variants",
      "Easy application and removal",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE / VCI-LDPE" },
      { label: "Thickness", value: "50 – 150 microns" },
      { label: "Standard Sizes", value: "1220 × 1220 × 1500mm" },
      { label: "Style", value: "Gusseted top cover" },
    ],
    tags: ["Made in India", "Custom Sizes", "Industrial Grade"],
    applications: ["Warehouse Storage", "Export Pallets", "Cold Storage", "Logistics", "Distribution Centers"],
  },
  {
    name: "Container Liner",
    num: "10",
    category: "Specialty Films",
    image: "/images/rayzor/products/container-liner.png",
    slug: "container-liner",
    shortDescription: "Heavy-duty container liners that transform shipping containers into clean, moisture-free environments.",
    description: "Our Container Liners are heavy-duty protective liners that transform standard 20ft and 40ft shipping containers into clean, moisture-free environments for your cargo. Essential for sea freight, these liners prevent contamination, condensation damage (container rain), and moisture ingress throughout the voyage. Available in single-layer LDPE and multi-layer aluminum foil laminate constructions, with features including zipper access doors and integrated desiccant pockets. Quick to install and remove, they are the industry standard for protecting bulk commodities, metal coils, machinery, and chemical products during international shipping.",
    gallery: [
      "/images/rayzor/products/container-liner.png",
      "/images/rayzor/products/foil-barrier-bag.png",
      "/images/rayzor/products/foil-vacuum-seal.png",
      "/images/rayzor/products/pallet-covers.png",
    ],
    features: [
      "Transforms containers into clean environments",
      "Prevents contamination during sea freight",
      "Complete moisture barrier protection",
      "Available for 20ft & 40ft containers",
      "Quick installation with zipper access",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE / Aluminum foil laminate" },
      { label: "Thickness", value: "100 – 200 microns" },
      { label: "Sizes", value: "20ft & 40ft container standard" },
      { label: "Features", value: "Zipper door, desiccant pockets" },
    ],
    tags: ["Made in India", "Custom Sizes", "Industrial Grade"],
    applications: ["Sea Freight", "Bulk Commodities", "Metal Coils", "Machinery Export", "Chemical Products"],
  },
  {
    name: "Shrink Film",
    num: "11",
    category: "Specialty Films",
    image: "/images/rayzor/products/shrink-film.png",
    slug: "shrink-film",
    shortDescription: "High-performance shrink film with tight product conformity, load stability, and tamper-evident sealing.",
    description: "Our Shrink Films are high-performance packaging films that tightly conform to product contours upon heat application, creating a secure, tamper-evident wrap. They ensure excellent load stability for palletized goods and provide a professional, retail-ready appearance for bundled products. Available in PE, PVC, and POF grades with shrink ratios up to 70%, and widths from 150mm to 3000mm. Whether you need to unitize pallet loads, bundle beverages, or wrap building materials, our shrink films deliver consistent performance on both manual and automatic shrink tunnels.",
    gallery: [
      "/images/rayzor/products/shrink-film.png",
      "/images/rayzor/products/shrink-film-roll.png",
      "/images/rayzor/products/pallet-wrap-apply.png",
    ],
    features: [
      "Conforms tightly to product contours",
      "High shrink ratio for secure fit",
      "Tamper-evident packaging",
      "Excellent clarity for product visibility",
      "Available in PVC, POF & PE grades",
    ],
    technicalSpecs: [
      { label: "Material", value: "PE / PVC / POF" },
      { label: "Thickness", value: "15 – 100 microns" },
      { label: "Shrink Ratio", value: "Up to 70%" },
      { label: "Width", value: "150mm – 3000mm" },
    ],
    tags: ["Made in India", "Custom Sizes", "Industrial Grade"],
    applications: ["Load Unitization", "Product Bundling", "Retail Display", "Beverage Industry", "Building Materials"],
  },
  {
    name: "Antistatic Films",
    num: "12",
    category: "Specialty Films",
    image: "/images/rayzor/products/antistatic-films.png",
    slug: "antistatic-films",
    shortDescription: "Specialized static-dissipative films for protecting sensitive electronics from ESD damage.",
    description: "Our Antistatic Films are specialized packaging materials engineered to safely dissipate static charges, preventing electrostatic discharge (ESD) damage to sensitive electronic components. The pink-tinted film allows easy visual identification on the production floor and in storage. Available as film rolls, pre-formed bags, and pouches, these products meet EIA-541 and MIL-B-81705C standards for static control packaging. With surface resistivity in the 10⁹ – 10¹² Ω/sq range, they provide reliable static protection for PCBs, semiconductors, medical devices, and telecommunications equipment.",
    gallery: [
      "/images/rayzor/products/antistatic-films.png",
      "/images/rayzor/products/ldpe-film-roll.png",
      "/images/rayzor/products/ldpe-pouch.png",
    ],
    features: [
      "Static dissipative properties",
      "Prevents electrostatic discharge (ESD)",
      "Pink tinted for easy identification",
      "Available in film, bags & pouches",
      "Meets EIA-541 & MIL-B-81705C standards",
    ],
    technicalSpecs: [
      { label: "Material", value: "LDPE + Antistatic agents" },
      { label: "Surface Resistivity", value: "10⁹ – 10¹² Ω/sq" },
      { label: "Thickness", value: "50 – 150 microns" },
      { label: "Color", value: "Pink (standard) / Custom" },
      { label: "Compliance", value: "EIA-541, MIL-B-81705C" },
    ],
    tags: ["Made in India", "ESD Safe", "Industrial Grade"],
    applications: ["Electronics", "Semiconductors", "PCB Assembly", "Medical Devices", "Telecommunications"],
  },
  {
    name: "VCI Shrink Films",
    num: "13",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-shrink-films.png",
    slug: "vci-shrink-films",
    shortDescription: "Dual-action shrink film combining load stability with active VCI corrosion protection for heavy machinery.",
    description: "Our VCI Shrink Films are an advanced dual-action packaging solution combining the load stability and weather resistance of shrink wrapping with the active corrosion protection of VCI technology. Designed for securing heavy machinery, military equipment, offshore installations, and mining equipment during long-term outdoor storage or international transit. The film shrinks tightly around irregular shapes upon heat application while continuously releasing corrosion inhibitors inside the enclosure. Available in widths up to 6000mm and thicknesses from 100 to 250 microns, with protection lasting up to 36 months in outdoor conditions.",
    gallery: [
      "/images/rayzor/products/vci-shrink-films.png",
      "/images/rayzor/products/shrink-film-roll.png",
      "/images/rayzor/products/vci-engine-wrap.png",
      "/images/rayzor/products/ldpe-machinery-cover.png",
    ],
    features: [
      "Dual-action: shrink wrap + VCI protection",
      "Secures heavy machinery during transit",
      "High shrink ratio with corrosion inhibition",
      "Transparent for easy inspection",
      "Long-term outdoor storage capability",
    ],
    technicalSpecs: [
      { label: "Material", value: "PE + VCI Additives" },
      { label: "Thickness", value: "100 – 250 microns" },
      { label: "Shrink Ratio", value: "Up to 50%" },
      { label: "Protection Period", value: "Up to 36 months" },
      { label: "Max Width", value: "Up to 6000mm" },
    ],
    tags: ["Made in India", "Custom Sizes", "Corrosion Resistant"],
    applications: ["Heavy Machinery", "Military Equipment", "Offshore Equipment", "Mining Equipment", "Long-term Storage"],
  },
  {
    name: "HM Pouches",
    num: "14",
    category: "Specialty Films",
    image: "/images/rayzor/products/hm-pouches.png",
    slug: "hm-pouches",
    shortDescription: "High Molecular pouches with superior tensile strength and puncture resistance for heavy components.",
    description: "Our HM (High Molecular) Pouches are manufactured from HM-HDPE resin, delivering significantly superior tensile strength and puncture resistance compared to standard LDPE pouches at equivalent or lower gauge thicknesses. This means you get equal or better protection while using less material — a cost-effective and eco-friendly advantage. Ideal for packaging heavy, sharp, or abrasive metal components, industrial hardware, and bulk items where standard LDPE would tear or puncture. Available in custom sizes with heat-seal closure.",
    gallery: [
      "/images/rayzor/products/hm-pouches.png",
      "/images/rayzor/products/ldpe-pouch.png",
      "/images/rayzor/products/ldpe-bags.png",
    ],
    features: [
      "Superior tensile strength vs standard LDPE",
      "Excellent puncture & tear resistance",
      "Thinner gauge with equal strength",
      "Cost-effective material reduction",
      "Suitable for heavy & sharp components",
    ],
    technicalSpecs: [
      { label: "Material", value: "HM-HDPE" },
      { label: "Thickness", value: "20 – 100 microns" },
      { label: "Tensile Strength", value: "30 – 45 MPa" },
      { label: "Sizes", value: "Custom" },
    ],
    tags: ["Made in India", "Custom Sizes", "Industrial Grade"],
    applications: ["Heavy Components", "Sharp Metal Parts", "Industrial Hardware", "Bulk Packaging", "Retail"],
  },
  {
    name: "PP Pouch",
    num: "15",
    category: "Specialty Films",
    image: "/images/rayzor/products/pp-pouch.png",
    slug: "pp-pouch",
    shortDescription: "Crystal-clear polypropylene pouches with high moisture barrier for premium product presentation.",
    description: "Our PP Pouches are manufactured from BOPP (Biaxially Oriented Polypropylene) and CPP (Cast Polypropylene) materials, delivering crystal-clear optical clarity and a high moisture barrier for premium product presentation. The crisp, glossy finish elevates the perceived value of packaged items, making these pouches ideal for garments, stationery, gift items, and pharmaceutical products. Heat-sealable at low temperatures for efficient production line integration, with options for resealable adhesive strips.",
    gallery: [
      "/images/rayzor/products/pp-pouch.png",
      "/images/rayzor/products/pp-film.png",
      "/images/rayzor/products/ldpe-pouch.png",
    ],
    features: [
      "Excellent optical clarity",
      "High moisture barrier",
      "Crisp, premium presentation",
      "Heat-sealable with low seal temperatures",
      "Available in BOPP & CPP grades",
    ],
    technicalSpecs: [
      { label: "Material", value: "BOPP / CPP" },
      { label: "Thickness", value: "20 – 80 microns" },
      { label: "Clarity", value: "Crystal clear" },
      { label: "Seal Temperature", value: "120 – 160°C" },
    ],
    tags: ["Made in India", "Custom Sizes", "Crystal Clear"],
    applications: ["Garments", "Stationery", "Food Packaging", "Gift Items", "Pharmaceutical"],
  },
  {
    name: "PP Film",
    num: "16",
    category: "Specialty Films",
    image: "/images/rayzor/products/pp-film.png",
    slug: "pp-film",
    shortDescription: "High-clarity PP film rolls for automated overwrapping with excellent stiffness and glossy finish.",
    description: "Our PP Film Rolls are high-clarity polypropylene films designed for automated overwrapping, lamination, and label applications. They offer excellent stiffness and machinability for high-speed packaging lines, superior sealability for consistent seam integrity, and a glossy finish that enhances product shelf appeal. Available in plain, metallized, and matte finish variants, with widths up to 1500mm and thicknesses from 15 to 60 microns. Widely used in the food industry for overwrapping confectionery and bakery products, as well as in tobacco, cosmetics, and general consumer goods packaging.",
    gallery: [
      "/images/rayzor/products/pp-film.png",
      "/images/rayzor/products/pp-pouch.png",
      "/images/rayzor/products/shrink-film-roll.png",
    ],
    features: [
      "High clarity & glossy finish",
      "Excellent stiffness for automated lines",
      "Superior sealability",
      "Low static charge buildup",
      "Available in plain & metallized variants",
    ],
    technicalSpecs: [
      { label: "Material", value: "BOPP / CPP" },
      { label: "Thickness", value: "15 – 60 microns" },
      { label: "Width", value: "Up to 1500mm" },
      { label: "Finish", value: "Glossy / Matte / Metallized" },
    ],
    tags: ["Made in India", "Custom Sizes", "High Clarity"],
    applications: ["Overwrapping", "Lamination", "Labels & Tapes", "Food Industry", "Tobacco Packaging"],
  },
];
