export const FALLBACK_PRODUCTS = [
  {
    name: "VCI Film Rolls",
    num: "01",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-film-roll.png",
    slug: "vci-film-rolls",
    description: "Industrial-grade VCI film rolls engineered for continuous automated packaging lines. Provides superior multimetal corrosion protection while maintaining excellent tensile strength and puncture resistance.",
  },
  {
    name: "VCI Pouch",
    num: "02",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-pouch.png",
    slug: "vci-pouch",
    description: "Pre-formed VCI pouches designed for rapid packaging of individual components. Ideal for spare parts, bearings, and small precision metal items requiring long-term rust prevention.",
  },
  {
    name: "VCI Bags",
    num: "03",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-bags.png",
    slug: "vci-bags",
    description: "Heavy-duty VCI bags for bulk packaging and larger components. Creates a dry, protective microclimate that actively neutralizes corrosive elements during shipping and storage.",
  },
  {
    name: "VCI Sheet",
    num: "04",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-sheet.png",
    slug: "vci-sheet",
    description: "Versatile VCI sheets used as interleaving for stacked metal parts or as protective liners for export crates. Provides immediate vapor-phase corrosion inhibition.",
  },
  {
    name: "LDPE Film Rolls",
    num: "05",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-film-roll.png",
    slug: "ldpe-film-rolls",
    description: "High-clarity, virgin LDPE film rolls offering exceptional stretch, tear resistance, and barrier properties. The foundation for secure, moisture-resistant industrial packaging.",
  },
  {
    name: "LDPE Pouch",
    num: "06",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-pouch.png",
    slug: "ldpe-pouch",
    description: "Durable LDPE pouches providing excellent moisture and dust barriers for individual items. Available in various thicknesses for different protection requirements.",
  },
  {
    name: "LDPE Bags",
    num: "07",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-bags.png",
    slug: "ldpe-bags",
    description: "Industrial-strength LDPE bags designed for bulk handling and secondary packaging. Excellent sealability and puncture resistance for heavy or sharp contents.",
  },
  {
    name: "LDPE Sheet",
    num: "08",
    category: "LDPE Packaging",
    image: "/images/rayzor/products/ldpe-sheet.png",
    slug: "ldpe-sheet",
    description: "Thick LDPE sheeting used for pallet capping, surface protection, and large-scale moisture barriers in export packaging applications.",
  },
  {
    name: "Pallet Covers",
    num: "09",
    category: "Specialty Films",
    image: "/images/rayzor/products/pallet-covers.png",
    slug: "pallet-covers",
    description: "Gusseted pallet covers designed to perfectly fit standard export pallets. Provides immediate protection against dust, dirt, and moisture during warehouse storage.",
  },
  {
    name: "Container Liner",
    num: "10",
    category: "Specialty Films",
    image: "/images/rayzor/products/container-liner.png",
    slug: "container-liner",
    description: "Heavy-duty bulk liners that transform standard shipping containers into clean, protective environments. Essential for preventing contamination and moisture damage during sea freight.",
  },
  {
    name: "Shrink Film",
    num: "11",
    category: "Specialty Films",
    image: "/images/rayzor/products/shrink-film.png",
    slug: "shrink-film",
    description: "High-performance shrink film that tightly conforms to product contours upon heat application. Ensures load stability and provides a tamper-evident, secure wrap.",
  },
  {
    name: "Antistatic Films",
    num: "12",
    category: "Specialty Films",
    image: "/images/rayzor/products/antistatic-films.png",
    slug: "antistatic-films",
    description: "Specialized films engineered to dissipate static charges. Critical for packaging sensitive electronic components and preventing electrostatic discharge (ESD) damage.",
  },
  {
    name: "VCI Shrink Films",
    num: "13",
    category: "VCI Protection",
    image: "/images/rayzor/products/vci-shrink-films.png",
    slug: "vci-shrink-films",
    description: "Advanced dual-action film combining the load stability of shrink wrapping with the active corrosion protection of VCI. The ultimate solution for securing heavy machinery.",
  },
  {
    name: "HM Pouches",
    num: "14",
    category: "Specialty Films",
    image: "/images/rayzor/products/hm-pouches.png",
    slug: "hm-pouches",
    description: "High Molecular (HM) pouches offering superior tensile strength and puncture resistance compared to standard LDPE. Ideal for heavy or sharp components.",
  },
  {
    name: "PP Pouch",
    num: "15",
    category: "Specialty Films",
    image: "/images/rayzor/products/pp-pouch.png",
    slug: "pp-pouch",
    description: "Polypropylene (PP) pouches providing excellent clarity and a high moisture barrier. Perfect for products requiring clear visibility and crisp presentation.",
  },
  {
    name: "PP Film",
    num: "16",
    category: "Specialty Films",
    image: "/images/rayzor/products/pp-film.png",
    slug: "pp-film",
    description: "High-clarity PP film rolls used for automated overwrapping. Offers excellent stiffness, sealability, and a glossy finish for premium product presentation.",
  },
];
